/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistemas;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //Plantilla Vacia

        System.out.println(new App().getGreeting());

    }
}
